package finals3;


import java.awt.*;
import javax.swing.*;
public class JFrame extends javax.swing.JFrame {

    // Creates new form JFrame

    
    double amt;
    int accNum;
    
    Account1 a1 = new Account1();
    Account2 a2 = new Account2();
    public JFrame() {
        initComponents();
        
        Color color = new Color(0, 102, 102);
        getContentPane().setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 249, 246));
        jLabel1.setText("Welcome to Bank of PaNice");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 215, 145));
        jButton1.setText("CHECK BALANCE");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 215, 145));
        jButton2.setText("DEPOSIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 215, 145));
        jButton3.setText("WITHDRAW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(240, 215, 145));
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(240, 215, 145));
        jButton5.setText("START");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\thinkpad T14\\Downloads\\7.png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // DEPOSIT BUTTON
        if (accNum == a1.getAccNum())
        {          
            try
            {
                amt = Double.parseDouble(JOptionPane.showInputDialog(null,
                "Enter Amount to Deposit", 
                "DEPOSIT", 3)); 
                int choice = JOptionPane.showConfirmDialog(null, "Are you sure?", 
                    "CONFIRMATION", JOptionPane.YES_NO_CANCEL_OPTION); 
                switch (choice) {
                    case JOptionPane.YES_OPTION:
                        a1.deposit(amt);
                        JOptionPane.showMessageDialog(null, "You have deposited " + amt);
                        JOptionPane.showMessageDialog(null,
                                "Deposited : " + amt +
                                        "\nCurrent Balance : " + a1.getBalance());
                        break;
                    case JOptionPane.NO_OPTION:
                        JOptionPane.showMessageDialog(null, "Changes not saved.");
                        JOptionPane.showMessageDialog(null,
                                "Current Balance : " + a1.getBalance());
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Operation canceled.");
                        break;
                } 
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, 
                "Please input a NUMBER", "ERROR", 0);
            }
                       
        }
        else if (accNum == a2.getAccNum())
        {

            try
            {
                amt = Double.parseDouble(JOptionPane.showInputDialog(null,
                    "Enter Amount to Deposit", 
                    "DEPOSIT", 3)); 
                int choice = JOptionPane.showConfirmDialog(null, "Are you sure?", 
                                                   "CONFIRMATION", JOptionPane.YES_NO_CANCEL_OPTION); 
                switch (choice) {
                    case JOptionPane.YES_OPTION:
                        a2.deposit(amt);
                        JOptionPane.showMessageDialog(null, "You have deposited " + amt );
                        JOptionPane.showMessageDialog(null,
                                "Deposited : " + amt +
                                        "\nCurrent Balance : " + a2.getBalance());
                        break;
                    case JOptionPane.NO_OPTION:
                        JOptionPane.showMessageDialog(null, "Changes not saved.");
                        JOptionPane.showMessageDialog(null,
                                "Current Balance : " + a2.getBalance());
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Operation canceled.");
                        break;
                } 
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, 
                    "Please input a NUMBER", "ERROR", 0);
            }
                       
        }
        else
        {
            JOptionPane.showMessageDialog(null, 
                    "Please open an account at (Bank Name)",
                    "ERROR", 0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // CHECK BALANCE
        if (accNum == a1.getAccNum())
        {
            JOptionPane.showMessageDialog(null, 
                            "Current Balance : " + a1.getBalance(),
                            "BALANCE CHECK", 1);
                    
        }
        else if (accNum == a2.getAccNum())
        {
            JOptionPane.showMessageDialog(null, 
                            "Current Balance : " + a2.getBalance(),
                            "BALANCE CHECK", 1);
                    
        }
        else
        {
            JOptionPane.showMessageDialog(null, 
                    "Please open an account at (Bank Name)",
                    "ERROR", 0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // WITHDRAW
        if (accNum == a1.getAccNum())
        {

            try
            {
                amt = Double.parseDouble(JOptionPane.showInputDialog(null,
                "Enter Amount to Withdraw", "WITHDRAW", 3)); 
                int choice = JOptionPane.showConfirmDialog(null, "Are you sure?", 
                                                   "CONFIRMATION", JOptionPane.YES_NO_CANCEL_OPTION); 
                switch (choice) {
                    case JOptionPane.YES_OPTION:
                        if (amt < a1.getBalance())
                        {
                            a1.withdraw(amt);
                            JOptionPane.showMessageDialog(null, "You have withdrawn " + amt );
                            JOptionPane.showMessageDialog(null,
                                    "Withdrawn : " + amt +
                                            "\nCurrent Balance : " + a1.getBalance());
                        }
                        else if (amt >= a1.getBalance())
                        {
                            JOptionPane.showMessageDialog(null,
                                    "Insufficient Funds", "ERROR", 0);
                            
                        }   break;
                    case JOptionPane.NO_OPTION:
                        JOptionPane.showMessageDialog(null, "Changes not saved.");
                        JOptionPane.showMessageDialog(null,
                                "Current Balance : " + a1.getBalance());
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Operation canceled.");
                        break; 
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, 
                 "Please input a NUMBER", "ERROR", 0);
            }
        }
        else if (accNum == a2.getAccNum())
        {

            try
            {
                amt = Double.parseDouble(JOptionPane.showInputDialog(null,
                    "Enter Amount to Withdraw", "WITHDRAW", 3)); 
                int choice = JOptionPane.showConfirmDialog(null, "Are you sure?", 
                                                   "CONFIRMATION", JOptionPane.YES_NO_CANCEL_OPTION); 
                switch (choice) {
                    case JOptionPane.YES_OPTION:
                        if (amt < a2.getBalance())
                        {
                            a2.withdraw(amt);
                            JOptionPane.showMessageDialog(null, "You have withdrawn " + amt);
                            JOptionPane.showMessageDialog(null,
                                    "Withdrawn : " + amt +
                                            "\nCurrent Balance : " + a2.getBalance());
                        }
                        else if (amt >= a2.getBalance())
                        {
                            JOptionPane.showMessageDialog(null,
                                    "Insufficient Funds", "ERROR", 0);
                            
                        }   break;
                    case JOptionPane.NO_OPTION:
                        JOptionPane.showMessageDialog(null, "Changes not saved.");
                        JOptionPane.showMessageDialog(null,
                                "Current Balance : " + a2.getBalance());
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Operation canceled.");
                        break; 
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, 
                    "Please input a NUMBER", "ERROR", 0);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, 
                    "Please open an account at (Bank Name)",
                    "ERROR", 0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Start Button
        // Open BankMain
        BankMain bankMain = new BankMain();
        
        try
        {
            accNum = Integer.parseInt(JOptionPane.showInputDialog(null, 
          "Please Enter Account Number",
           "Welcome to BankOOP", 1));
            if (accNum == a1.getAccNum())
            {
          
                bankMain.setVisible(true); // display bankMain here
               
                dispose();
                System.out.println("Account Opened.");
                JOptionPane.showMessageDialog(null, 
                    "Name : " + a1.getName() +
                    "\nAddress : " + a1.getAddress() + 
                    "\nEmail : " + a1.getEmail() + 
                    "\nContact Number : " + a1.getContactNum() + 
                    "\nDate of Birth : " + a1.getBirthday(),
                    "PERSONAL INFORMATION", 1);
            }
            else if (accNum == a2.getAccNum())
            {
                bankMain.show(); // display bankMain here
                dispose();
                System.out.println("Account Opened.");
                JOptionPane.showMessageDialog(null, 
                    "Name : " + a2.getName() +
                    "\nAddress : " + a2.getAddress() + 
                    "\nEmail : " + a2.getEmail() + 
                    "\nContact Number : " + a2.getContactNum() + 
                    "\nDate of Birth : " + a2.getBirthday(),
                    "PERSONAL INFORMATION", 1);
            }
            else
            {
                JOptionPane.showMessageDialog(null, 
                    "Please open an account at (Bank Name)",
                    "ERROR", 0);
            }
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, 
                 "Please input a 3-DIGIT ACCOUNT NUMBER", 
                 "ERROR", 0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame f = new JFrame();
                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                f.setPreferredSize(new Dimension(420, 510));
                f.setResizable(false);
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
